### Login to get token
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### Test start reconciliation process with token from login
POST http://localhost:3000/api/rekon-wt-harian
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NDk3MjM1MSwiZXhwIjoxNzU1MDU4NzUxfQ.PlsGiqGkDyN8ly5yEqsQRPBRBtk8-qmUPJI87y6UHmM

{
  "cab": "G033",
  "periode": "2508"
}

### Test get reconciliation results with token from login
GET http://localhost:3000/api/rekon-wt-harian/2508/All
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NDk3MjM1MSwiZXhwIjoxNzU1MDU4NzUxfQ.PlsGiqGkDyN8ly5yEqsQRPBRBtk8-qmUPJI87y6UHmM

### Test get summary of reconciliation results with token from login
GET http://localhost:3000/api/rekon-wt-harian/G001/2507/summary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU0NDUzMTExLCJleHAiOjE3NTQ1Mzk1MTF9.pNDWTaSlvek7BIEnMUPrbV3Y80BpB-yv0pAhWHyoDDU

### Test delete reconciliation results with token from login
DELETE http://localhost:3000/api/rekon-wt-harian/G001/2507
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU0NDUzMTExLCJleHAiOjE3NTQ1Mzk1MTF9.pNDWTaSlvek7BIEnMUPrbV3Y80BpB-yv0pAhWHyoDDU