### Get JWT token (login)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### Get all rekon_virtual
//coba screening rekon_virtual
GET http://localhost:3000/api/rekon-virtual-mrg/screening?cabang=G033&periode=2510
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MDY5MTg0MiwiZXhwIjoxNzYwNzc4MjQyfQ.jQyktVF9TtyTJ1BreKpUIXv7dj0_2qIw6akbJPlDnss

### trial update recid
PUT http://localhost:3000/api/rekon-virtual-mrg/recid
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MDY5MTg0MiwiZXhwIjoxNzYwNzc4MjQyfQ.jQyktVF9TtyTJ1BreKpUIXv7dj0_2qIw6akbJPlDnss

{
  "recid": "1",
  "cabang": "G033",
  "periode": "2510",
  "prdcd": "20103597",
  "shop": "TVHV",
  "tanggal": "2025-10-01"
}

### sync all
POST http://localhost:3000/api/rekon-virtual-mrg/sync-all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3NjkzMDIxMCwiZXhwIjoxNzc3MDE2NjEwfQ.lz7qyRU0r2E_WrUkjE-2U07FqjvIor91DcHRL2jW1us